version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - microservice-network
    depends_on:
      - service-auth
      - service-user

  service-auth:
    build: ./service-auth
    container_name: service-auth
    expose:
      - "4000"
    env_file:
      - ./service-auth/.env
    networks:
      - microservice-network
    depends_on:
      - service-user

  service-user:
    build: ./service-user
    container_name: service-user
    expose:
      - "5000"
    env_file:
      - ./service-user/.env
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
